version: '3.4'

services:
    stackexchangeapi:
        image: ${DOCKER_REGISTRY-}stackexchangeapi

        depends_on:
            postgres:
                condition: service_healthy

        ports:
            - "8100:8080"

        build:
            context: .
            dockerfile: StackExchangeApi/Dockerfile

        networks:
            - stackexchangeapi

    postgres:
        image: postgres:latest

        ports:
            - "5432:5432"

        volumes:
            - db_volume:/var/lib/postgresql/data

        environment:
            POSTGRES_USER: "postgres"
            POSTGRES_PASSWORD: "postgres"
            POSTGRES_DB: "Tags"
        
        networks:
            - stackexchangeapi
        
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 10s
            timeout: 5s
            retries: 5

networks:
    stackexchangeapi:
        driver: bridge

volumes:
    db_volume: