version: '3.4'

services:
  stackexchangeapi:
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_HTTP_PORTS=8080
      - ConnectionStrings__DefaultConnection=Host=postgres; Port=5432; Database=Tags; User Id=postgres; Password=postgres
      - NumberOfTagsInDatabase=500
      - MaxPageSize=50
      - StackExchange__ApiUrl=https://api.stackexchange.com/2.3/tags
      - StackExchange__PageSize=100
    ports:
      - "8080"